version: "2"
linters:
  enable:
    - bodyclose
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - whitespace
    - staticcheck
    - ineffassign
    - unused
  disable:
    - errcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - bin
      - docs
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - bin
      - docs
      - third_party$
      - builtin$
      - examples$
run:
  timeout: 3m
